// <auto-generated />
using System;
using Desafio1DSE_AM200230_RJ202336.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio1DSE_AM200230_RJ202336.Migrations
{
    [DbContext(typeof(EmpleadosDBContext))]
    partial class EmpleadosDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desafio1DSE_AM200230_RJ202336.Models.Departamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DescripcionDepartamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            NombreDepartamento = "Recursos Humanos"
                        },
                        new
                        {
                            ID = 2,
                            NombreDepartamento = "Tecnología"
                        },
                        new
                        {
                            ID = 3,
                            NombreDepartamento = "Ventas"
                        });
                });

            modelBuilder.Entity("Desafio1DSE_AM200230_RJ202336.Models.Empleado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DepartamentoId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("DesciprionEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SalarioEmpleado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartamentoId = 1,
                            FechaContratacion = new DateTime(2010, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreEmpleado = "John Doe",
                            SalarioEmpleado = 50000m
                        },
                        new
                        {
                            ID = 2,
                            DepartamentoId = 2,
                            FechaContratacion = new DateTime(2015, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1990, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreEmpleado = "Jane Smith",
                            SalarioEmpleado = 70000m
                        },
                        new
                        {
                            ID = 3,
                            DepartamentoId = 3,
                            FechaContratacion = new DateTime(2012, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1982, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreEmpleado = "Mark Johnson",
                            SalarioEmpleado = 55000m
                        },
                        new
                        {
                            ID = 4,
                            DepartamentoId = 1,
                            FechaContratacion = new DateTime(2005, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1978, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreEmpleado = "Emily Davis",
                            SalarioEmpleado = 75000m
                        },
                        new
                        {
                            ID = 5,
                            DepartamentoId = 2,
                            FechaContratacion = new DateTime(2020, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateTime(1995, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreEmpleado = "Michael Brown",
                            SalarioEmpleado = 60000m
                        });
                });

            modelBuilder.Entity("Desafio1DSE_AM200230_RJ202336.Models.Empleado", b =>
                {
                    b.HasOne("Desafio1DSE_AM200230_RJ202336.Models.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Desafio1DSE_AM200230_RJ202336.Models.Departamento", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
